package io.github.julystar.musicapp.migration

internal object LegacyEnvironmentVariables {
    const val DEVELOPER_MODE = "TIDETUNES_DEVELOPER_MODE"
    const val ONEDRIVE_CLIENT_ID = "TIDETUNES_ONEDRIVE_ID"
    const val SMB_TEST_AUTH_URL = "TIDETUNES_SMB_TEST_AUTH_URL"
    const val SMB_TEST_GUEST_URL = "TIDETUNES_SMB_TEST_GUEST_URL"
    const val SMB_TEST_USERNAME = "TIDETUNES_SMB_TEST_USERNAME"
    const val SMB_TEST_PASSWORD = "TIDETUNES_SMB_TEST_PASSWORD"
    const val SMB_TEST_FIXTURE_DIR = "TIDETUNES_SMB_TEST_FIXTURE_DIR"
    const val WEBDAV_ADDRESS = "TIDETUNES_WEBDAV_ADDRESS"
    const val WEBDAV_USERNAME = "TIDETUNES_WEBDAV_USERNAME"
    const val WEBDAV_PASSWORD = "TIDETUNES_WEBDAV_PASSWORD"
}
