package com.github.tidetunes.plugin.runtime

sealed class PluginRuntimeError(message:String,cause:Throwable?=null):Exception(message,cause){class Closed(m:String,c:Throwable?=null):PluginRuntimeError(m,c);class Initialization(m:String,c:Throwable?=null):PluginRuntimeError(m,c);class Script(m:String,c:Throwable?=null):PluginRuntimeError(m,c);class FunctionNotFound(m:String,c:Throwable?=null):PluginRuntimeError(m,c);class InvalidRequest(m:String,c:Throwable?=null):PluginRuntimeError(m,c);class Timeout(m:String,c:Throwable?=null):PluginRuntimeError(m,c);class Cancelled(m:String,c:Throwable?=null):PluginRuntimeError(m,c);class OutOfMemory(m:String,c:Throwable?=null):PluginRuntimeError(m,c);class HostApi(m:String,c:Throwable?=null):PluginRuntimeError(m,c);class Poisoned(m:String,c:Throwable?=null):PluginRuntimeError(m,c);class Internal(m:String,c:Throwable?=null):PluginRuntimeError(m,c)}
internal fun Throwable.toPluginRuntimeError():PluginRuntimeError{val m=message.orEmpty();val n=this::class.simpleName.orEmpty();return when{n.contains("FunctionNotFound")->PluginRuntimeError.FunctionNotFound(m,this);n.contains("InvalidRequest")->PluginRuntimeError.InvalidRequest(m,this);n.contains("OutOfMemory")->PluginRuntimeError.OutOfMemory(m,this);n.contains("Initialization")->PluginRuntimeError.Initialization(m,this);n.contains("Cancelled")->PluginRuntimeError.Cancelled(m,this);n.contains("Timeout")->PluginRuntimeError.Timeout(m,this);n.contains("Poisoned")->PluginRuntimeError.Poisoned(m,this);n.contains("HostApi")->PluginRuntimeError.HostApi(m,this);n.contains("Closed")->PluginRuntimeError.Closed(m,this);n.contains("Script")->PluginRuntimeError.Script(m,this);else->PluginRuntimeError.Internal(m.ifBlank{"Plugin runtime failed"},this)}}
internal fun PluginRuntimeError.requiresRuntimeRebuild(): Boolean =
    this is PluginRuntimeError.Timeout ||
        this is PluginRuntimeError.OutOfMemory ||
        this is PluginRuntimeError.Poisoned ||
        this is PluginRuntimeError.Internal
