[package]
name = "tidetunes-metadata"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
publish = false

[dependencies]
bytes = "1.5.0"
lofty = "0.24.0"
thiserror = { workspace = true }
tidetunes-remote-storage = { path = "../tidetunes-remote-storage" }
tidetunes-runtime = { workspace = true }

[dev-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
