#include "quickjs_compat.h"
#include "quickjs.h"
#include <stdlib.h>
#include <string.h>
struct TTQuickJs { JSRuntime *rt; JSContext *ctx; TTQjsOptions options; };
static char *copy_string(const char *s, size_t n) { char *p=(char*)malloc(n+1); if(!p)return NULL; memcpy(p,s,n); p[n]=0; return p; }
static void set_error(char **out, const char *s) { if(out) *out=copy_string(s,strlen(s)); }
static char *value_string(JSContext *ctx, JSValueConst v) { size_t n=0; const char *s=JS_ToCStringLen(ctx,&n,v); if(!s)return NULL; char *r=copy_string(s,n); JS_FreeCString(ctx,s); return r; }
static char *exception_string(JSContext *ctx) { JSValue e=JS_GetException(ctx); char *m=value_string(ctx,e); JSValue st=JS_GetPropertyStr(ctx,e,"stack"); char *s=JS_IsUndefined(st)?NULL:value_string(ctx,st); size_t ml=m?strlen(m):0, sl=s?strlen(s):0; char *r=(char*)malloc(ml+sl+2); if(r){ if(ml)memcpy(r,m,ml); if(ml&&sl)r[ml++]='\n'; if(sl)memcpy(r+ml,s,sl); r[ml+sl]=0; } free(m); free(s); JS_FreeValue(ctx,st); JS_FreeValue(ctx,e); return r?r:copy_string("JavaScript execution failed",27); }
static int interrupt_cb(JSRuntime *rt, void *opaque) { (void)rt; TTQuickJs *q=(TTQuickJs*)opaque; return q->options.should_interrupt ? q->options.should_interrupt(q->options.opaque) : 0; }
static JSValue host_cb(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) { (void)this_val; TTQuickJs *q=(TTQuickJs*)JS_GetContextOpaque(ctx); if(!q||!q->options.host_call||argc<2)return JS_ThrowInternalError(ctx,"Host API unavailable"); size_t nn=0,pn=0; const char *n=JS_ToCStringLen(ctx,&nn,argv[0]), *p=JS_ToCStringLen(ctx,&pn,argv[1]); if(!n||!p){if(n)JS_FreeCString(ctx,n);if(p)JS_FreeCString(ctx,p);return JS_EXCEPTION;} TTQjsStringView result={0},error={0}; int rc=q->options.host_call(q->options.opaque,(TTQjsStringView){n,nn},(TTQjsStringView){p,pn},&result,&error); JS_FreeCString(ctx,n);JS_FreeCString(ctx,p); if(rc!=0){return JS_ThrowInternalError(ctx,"%.*s",(int)error.length,error.data?error.data:"Host API failed");} return JS_NewStringLen(ctx,result.data?result.data:"",result.length); }
TTQuickJs *tt_qjs_create(const TTQjsOptions *o,char **error){TTQuickJs*q=(TTQuickJs*)calloc(1,sizeof(*q));if(!q){set_error(error,"allocation failed");return NULL;}if(o)q->options=*o;q->rt=JS_NewRuntime();if(!q->rt){free(q);set_error(error,"runtime initialization failed");return NULL;}if(o&&o->memory_limit_bytes)JS_SetMemoryLimit(q->rt,(size_t)o->memory_limit_bytes);if(o&&o->stack_limit_bytes)JS_SetMaxStackSize(q->rt,(size_t)o->stack_limit_bytes);JS_SetInterruptHandler(q->rt,interrupt_cb,q);q->ctx=JS_NewContext(q->rt);if(!q->ctx){JS_FreeRuntime(q->rt);free(q);set_error(error,"context initialization failed");return NULL;}JS_SetContextOpaque(q->ctx,q);JSValue g=JS_GetGlobalObject(q->ctx);JS_SetPropertyStr(q->ctx,g,"__lyricoHostCall",JS_NewCFunction(q->ctx,host_cb,"__lyricoHostCall",2));JS_FreeValue(q->ctx,g);return q;}
int tt_qjs_eval(TTQuickJs*q,const char*s,size_t n,const char*f,char**result,char**error){if(!q){set_error(error,"runtime closed");return 1;}JS_UpdateStackTop(q->rt);JSValue v=JS_Eval(q->ctx,s,n,f?f:"<plugin>",JS_EVAL_TYPE_GLOBAL);if(JS_IsException(v)){*error=exception_string(q->ctx);JS_FreeValue(q->ctx,v);return 1;}*result=value_string(q->ctx,v);JS_FreeValue(q->ctx,v);return 0;}
int tt_qjs_call_json(TTQuickJs*q,const char*fn,const char*json,size_t n,char**result,char**error){if(!q){set_error(error,"runtime closed");return 1;}JS_UpdateStackTop(q->rt);JSValue g=JS_GetGlobalObject(q->ctx),f=JS_GetPropertyStr(q->ctx,g,fn);if(!JS_IsFunction(q->ctx,f)){set_error(error,"function not found");JS_FreeValue(q->ctx,f);JS_FreeValue(q->ctx,g);return 2;}JSValue req=JS_ParseJSON(q->ctx,json,n,"<request>");if(JS_IsException(req)){*error=exception_string(q->ctx);JS_FreeValue(q->ctx,f);JS_FreeValue(q->ctx,g);return 3;}JSValue v=JS_Call(q->ctx,f,JS_UNDEFINED,1,&req);JS_FreeValue(q->ctx,req);if(JS_IsException(v)){*error=exception_string(q->ctx);JS_FreeValue(q->ctx,v);JS_FreeValue(q->ctx,f);JS_FreeValue(q->ctx,g);return 1;}if(JS_IsUndefined(v)){*result=copy_string("null",4);}else{JSValue j=JS_JSONStringify(q->ctx,v,JS_UNDEFINED,JS_UNDEFINED);if(JS_IsException(j)){*error=exception_string(q->ctx);JS_FreeValue(q->ctx,j);JS_FreeValue(q->ctx,v);JS_FreeValue(q->ctx,f);JS_FreeValue(q->ctx,g);return 1;}*result=JS_IsUndefined(j)?copy_string("null",4):value_string(q->ctx,j);JS_FreeValue(q->ctx,j);}JS_FreeValue(q->ctx,v);JS_FreeValue(q->ctx,f);JS_FreeValue(q->ctx,g);return 0;}
void tt_qjs_free_string(char*v){free(v);} void tt_qjs_destroy(TTQuickJs*q){if(!q)return;if(q->ctx)JS_FreeContext(q->ctx);if(q->rt)JS_FreeRuntime(q->rt);free(q);}
