package com.github.tidetunes.core.presentation.theme

import androidx.compose.ui.graphics.Color
import top.yukonga.miuix.kmp.theme.Colors

/**
 * Shared brand tokens from Design/docs/TideTunes-PDS-v3.md and the Figma Make design system.
 * Keep these public so feature modules can use the same TideTunes visual language without
 * duplicating hex values.
 */
object TideTunesBrand {
    val Primary = Color(0xFFFF5B8A)
    val Secondary = Color(0xFF7A6CFF)
    val SupportBlue = Color(0xFF3B82F6)
    val SupportOrange = Color(0xFFF59E0B)
    val SupportGreen = Color(0xFF10B981)
}

internal val TideTunesLightColors = Colors(
    primary = TideTunesBrand.Primary,
    onPrimary = Color.White,
    primaryVariant = TideTunesBrand.Secondary,
    onPrimaryVariant = Color.White,
    error = Color(0xFFEF4444),
    onError = Color.White,
    errorContainer = Color(0xFFFFF0F4),
    onErrorContainer = Color(0xFFD91F55),
    disabledPrimary = Color(0xFFB8B8C1),
    disabledOnPrimary = Color(0xFFF7F8FA),
    disabledPrimaryButton = Color(0xFFB8B8C1),
    disabledOnPrimaryButton = Color.White,
    disabledPrimarySlider = Color(0xFFB8B8C1),
    primaryContainer = TideTunesBrand.Primary,
    onPrimaryContainer = Color.White,
    secondary = Color(0xFFEFEFF2),
    onSecondary = Color(0xFF1A1A1F),
    secondaryVariant = Color(0xFFF2F3F6),
    onSecondaryVariant = Color(0xFF1A1A1F),
    disabledSecondary = Color(0xFFF2F3F6),
    disabledOnSecondary = Color(0xFFB8B8C1),
    disabledSecondaryVariant = Color(0xFFF2F3F6),
    disabledOnSecondaryVariant = Color(0xFFB8B8C1),
    secondaryContainer = Color(0xFFF7F8FA),
    onSecondaryContainer = Color(0xFF1A1A1F),
    secondaryContainerVariant = Color(0xFFF2F3F6),
    onSecondaryContainerVariant = Color(0xFF6B6B75),
    tertiaryContainer = Color(0xFFFFEEF5),
    onTertiaryContainer = TideTunesBrand.Primary,
    tertiaryContainerVariant = Color(0xFFF2F3F6),
    background = Color(0xFFFFFFFF),
    onBackground = Color(0xFF1A1A1F),
    onBackgroundVariant = Color(0xFF6B6B75),
    surface = Color(0xFFFAFAFC),
    onSurface = Color(0xFF1A1A1F),
    surfaceVariant = Color(0xFFE8E8ED),
    onSurfaceSecondary = Color(0xFF6B6B75),
    onSurfaceVariantSummary = Color(0xFF6B6B75),
    onSurfaceVariantActions = Color(0xFF9A9AA3),
    disabledOnSurface = Color(0xFFB8B8C1),
    surfaceContainer = Color(0xFFFFFFFF),
    onSurfaceContainer = Color(0xFF1A1A1F),
    onSurfaceContainerVariant = Color(0xFF6B6B75),
    surfaceContainerHigh = Color(0xFFF7F8FA),
    onSurfaceContainerHigh = Color(0xFF6B6B75),
    surfaceContainerHighest = Color(0xFFF2F3F6),
    onSurfaceContainerHighest = Color(0xFF1A1A1F),
    outline = Color(0xFFE8E8ED),
    dividerLine = Color(0xFFEFEFF2),
    windowDimming = Color.Black.copy(alpha = 0.32f),
    sliderKeyPoint = Color(0xFFB8B8C1).copy(alpha = 0.3f),
    sliderKeyPointForeground = TideTunesBrand.Primary,
    sliderBackground = Color.Black.copy(alpha = 0.08f),
)

internal val TideTunesDarkColors = Colors(
    primary = Color(0xFFFF7AA8),
    onPrimary = Color(0xFF0B0B0F),
    primaryVariant = Color(0xFF9A90FF),
    onPrimaryVariant = Color.White,
    error = Color(0xFFEF4444),
    onError = Color.White,
    errorContainer = Color(0xFF3A1B27),
    onErrorContainer = Color(0xFFFF8FB0),
    disabledPrimary = Color(0xFF5A5A64),
    disabledOnPrimary = Color(0xFF16161D),
    disabledPrimaryButton = Color(0xFF45454E),
    disabledOnPrimaryButton = Color(0xFF7D7D88),
    disabledPrimarySlider = Color(0xFF45454E),
    primaryContainer = Color(0xFFFF7AA8),
    onPrimaryContainer = Color(0xFF0B0B0F),
    secondary = Color(0xFF2A2A35),
    onSecondary = Color(0xFFF5F5F7),
    secondaryVariant = Color(0xFF2A2A35),
    onSecondaryVariant = Color(0xFFF5F5F7),
    disabledSecondary = Color(0xFF16161D),
    disabledOnSecondary = Color(0xFF5A5A64),
    disabledSecondaryVariant = Color(0xFF1F1F28),
    disabledOnSecondaryVariant = Color(0xFF5A5A64),
    secondaryContainer = Color(0xFF16161D),
    onSecondaryContainer = Color(0xFFF5F5F7),
    secondaryContainerVariant = Color(0xFF2A2A35),
    onSecondaryContainerVariant = Color(0xFF9A9AA3),
    tertiaryContainer = Color(0xFF3A1B27),
    onTertiaryContainer = Color(0xFFFF8FB0),
    tertiaryContainerVariant = Color(0xFF2A2A35),
    background = Color(0xFF0B0B0F),
    onBackground = Color(0xFFF5F5F7),
    onBackgroundVariant = Color(0xFF9A9AA3),
    surface = Color(0xFF111118),
    onSurface = Color(0xFFF5F5F7),
    surfaceVariant = Color(0xFF2A2A35),
    onSurfaceSecondary = Color(0xFF9A9AA3),
    onSurfaceVariantSummary = Color(0xFF9A9AA3),
    onSurfaceVariantActions = Color(0xFF6B6B75),
    disabledOnSurface = Color(0xFF5A5A64),
    surfaceContainer = Color(0xFF16161D),
    onSurfaceContainer = Color(0xFFF5F5F7),
    onSurfaceContainerVariant = Color(0xFF9A9AA3),
    surfaceContainerHigh = Color(0xFF1F1F28),
    onSurfaceContainerHigh = Color(0xFF9A9AA3),
    surfaceContainerHighest = Color(0xFF2A2A35),
    onSurfaceContainerHighest = Color(0xFFF5F5F7),
    outline = Color(0xFF2A2A35),
    dividerLine = Color(0xFF1F1F28),
    windowDimming = Color.Black.copy(alpha = 0.7f),
    sliderKeyPoint = Color(0xFF7D7D88).copy(alpha = 0.35f),
    sliderKeyPointForeground = Color(0xFFFF7AA8),
    sliderBackground = Color.White.copy(alpha = 0.12f),
)
